### ISSUE TITLE
refacto user migration

### ISSUE THREAD

**Issue by AugustinSeguin** [Eco-Gest/Backend-Laravel#13]
- delete on cascade quand on delete le user : ne pas supprimer les posts du user 
- ajouter un nom utilisateur unique sur la migration de la user table

**Comment by eleonoreeuzenes** [comment]
@AugustinSeguin est-ce que cette story inclus aussi de renvoyer une erreur :
        if (User::where('username', $request['username'])->count() > 0) {
            return response()->json([
                'message' => 'Username already used.'
            ], 409);
        }

dans le update du usercontroller ?

**Comment by AugustinSeguin** [comment]
@eleonoreeuzenes non je comptais uniquement rajouter un appel à la fonction unique() pour la migration de la table user, exactement comme ça a été fait sur l'email par exemple. Ce qui fait que si le username existe déjà Eloquent renverra une erreur ;)

**Comment by eleonoreeuzenes** [comment]
Ah non faut pas supprimer je l'utilise côté front 😆
